stages:
    - b&p acr
    - deploy to aks
#variables:
  #IMAGE_TAG: $CI_COMMIT_REF_SLUG
    
docker_build:
    stage: b&p acr
    image: docker:latest
    services:
      - docker:dind # allows developers to run a Docker container within an already running Docker container to support CI/CD pipelines.
    script:
      - export TAG=$(git rev-parse --short HEAD)
      #- docker build -t $ACR_REGISTRY_IMAGE:$IMAGE_TAG .
      - docker build -t $ACR_REGISTRY_IMAGE:$TAG .
      - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY_URL --username $CI_REGISTRY_USER --password-stdin
      #- docker push $ACR_REGISTRY_IMAGE:$IMAGE_TAG
      - docker push $ACR_REGISTRY_IMAGE:$TAG

deploy:
  stage: deploy to aks
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - echo "$KUBE_CONFIG" > kubeconfig.yml
    #- sed -i "s/__IMAGE_TAG__/$IMAGE_TAG/g" $KUBE_DEPLOYMENT_FILE
    - kubectl --kubeconfig=kubeconfig.yml apply -f $KUBE_DEPLOYMENT_FILE

