---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
        - name: drupal
          image: materialdash.azurecr.io/drupal:__IMAGE_TAG__
          command: ["apache2-foreground"]
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_DATABASE
              value: "drupal"
            - name: MYSQL_USER
              value: "drupaluser"
            - name: MYSQL_PASSWORD
              value: "12345"
            - name: MYSQL_HOST
              value: "mysql-service"
      imagePullSecrets:
        - name: notekey 
---
apiVersion: v1
kind: Service
metadata:
  name: drupal
spec:
  selector:
    app: drupal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
