---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "12345"
            - name: MYSQL_DATABASE
              value: "drupal"
            - name: MYSQL_USER
              value: "drupaluser"
            - name: MYSQL_PASSWORD
              value: "12345"
            - name: MYSQL_HOST
              value: "mysql-service"
      imagePullSecrets:
        - name: drupalkey

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    -
      name: mysql
      port: 3306
      protocol: TCP
  selector:
    app: mysql
