name: Drupal application
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build docker container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Azure ACR
        uses: Azure/docker-login@v1
        with:
          login-server: myclusterss.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push docker image
        run: |
          docker build . -t myclusterss.azurecr.io/drupal:${{ github.run_number }}
          docker push myclusterss.azurecr.io/drupal:${{ github.run_number }} 

      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

      - name: Apply Kustomization
        run: |
          kustomize build . | kubectl apply -f .
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }} 

     # - name: deploy image into aks
     #   run: |
        
              
     # - uses: Azure/k8s-set-context@v2
     #   with:
     #      kubeconfig: ${{ secrets.KUBE_CONFIG }}  

     # - uses: azure/setup-kubectl@v2.0

     # - name: Apply Kustomization File
     #   run: |
     #     kubectl apply -k .  
      # kubectl apply -f deployment.yml

          
    #  - name: deploy into aks
    #    uses: Azure/k8s-deploy@v4
    #    with:
    #       action: deploy
    #       manifests: |
    #          deployment.yml
    #       images: |
    #           myclusterss.azurecr.io/drupal:${{ github.run_number }}
              
    #  - name: Deploy into AKS
    #    uses: Azure/k8s-deploy@v4
    #    with:
    #       action: deploy
    #       manifests: |
    #          deployment.yml     
    #       images: |
    #           myclusterss.azurecr.io/drupal:${{ github.run_number }}
  
              
