name: Drupal application
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build docker container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Azure ACR
        uses: Azure/docker-login@v1
        with:
          login-server: myclusterss.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push docker image
        run: |
          docker build . -t myclusterss.azurecr.io/drupal:${{ github.run_number }}
          docker push myclusterss.azurecr.io/drupal:${{ github.run_number }} 
          
      - uses: azure/setup-kubectl@v2.0

      - uses: Azure/k8s-set-context@v2
        with:
           kubeconfig: ${{ secrets.KUBE_CONFIG }}  

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Deploy
        run: |-
          ./kustomize edit set image  myclusterss.azurecr.io./drupal:${{ github.run_number }}
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/deployment.yml
          kubectl get services -o wide

     # - name: Run kustomize build
     #   run: |
     #     kustomize build .
     #     working-directory: ${{ github.workspace }}
              
     # - name: Deploy into AKS
     #   uses: Azure/k8s-deploy@v4
     #   with:
     #      action: deploy
     #      manifests: |
      #        deployment.yml
       #    images: |
       #        myclusterss.azurecr.io/drupal:${{ github.run_number }}
     # - name: Apply Kubernetes Manifests
     #   run: |
     #     kustomize build .

     # - name: Deploy using Kustomize
      #  run: |
       #   kubectl apply -k ./
        #  kubectl get all
              
