name: Drupal application
on: [push]
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - name: checkout
         - uses: actions/checkout@master
         - uses: Azure/docker-login@v1
           with:
              login-server: myclusterss.azurecr.io
              username: ${{ secrets.REGISTRY_USERNAME }}
              password: ${{ secrets.REGISTRY_PASSWORD }}

         - run: |
              docker build . -t myclusterss.azurecr.io/drupal:${{ github.run_number }}
              docker push myclusterss.azurecr.io/drupal:${{ github.run_number }}
              
