name: Drupal application

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build docker container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Azure ACR
        uses: Azure/docker-login@v1
        with:
          login-server: myclusterss.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push docker image
        run: |
          docker build . -t myclusterss.azurecr.io/drupal:${{ github.run_number }}
          docker push myclusterss.azurecr.io/drupal:${{ github.run_number }}              
